#!/bin/sh -x
TAG="$1"
rm -rf dist *.egg*info *.dist*info

git tag -a v${TAG} -m "version ${TAG}"
sed -i "s,\(version=.\).+\",version=\"$TAG\",g" setup.py
sed -i "s,\(version=.\).+\",version=\"$TAG\",g" setup-test.py

python3 setup-test.py sdist bdist_wheel

OK=0
python3 -m twine upload --repository testpypi dist/* && OK=1

if [ $OK -eq 0 ]
then
	exit 1
fi

rm -rf dist *.egg*info *.dist*info

python3 setup.py sdist bdist_wheel

python3 -m twine upload dist/*
